apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: khushieee4/backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: COOKIE_SECURE
          value: "false"
        - name: PORT
          value: "3000"
        - name: CORS_ORIGIN
          value: "http://3.6.219.175:30007"
        - name: MONGO
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: MONGO
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: JWT_SECRET
        - name: FIREBASE_SERVICE_ACCOUNT_JSON
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: FIREBASE_SERVICE_ACCOUNT_JSON
